# Generated by Django 3.2.9 on 2021-12-04 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecognizeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('transcript', models.TextField(blank=True, null=True, verbose_name='transcript')),
                ('transcript_with_timestamps', models.TextField(blank=True, null=True, verbose_name='transcript with timestamps')),
                ('video', models.FileField(upload_to='videos', verbose_name='video')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
