# Generated by Django 3.2.9 on 2021-12-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecognizeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='title')),
                ('topic', models.CharField(max_length=1000, verbose_name='topic')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('transcript', models.TextField(blank=True, null=True, verbose_name='transcript')),
                ('transcript_by_keywords', models.TextField(blank=True, null=True, verbose_name='transcript by keywords')),
                ('transcript_with_timestamps', models.TextField(blank=True, null=True, verbose_name='transcript with timestamps')),
                ('video', models.FileField(upload_to='videos', verbose_name='video')),
            ],
        ),
    ]
