# Generated by Django 3.2.9 on 2021-12-03 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recognize_videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recognizevideo',
            name='title',
        ),
        migrations.RemoveField(
            model_name='recognizevideo',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='recognizevideo',
            name='transcript_by_keywords',
        ),
    ]
